# Generated by Django 2.2.1 on 2019-09-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbCfgType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_type_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'db_cfg_types',
            },
        ),
        migrations.CreateModel(
            name='DbCfgDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('pass_word', models.CharField(max_length=2000)),
                ('db_cfg', models.CharField(max_length=2000)),
                ('is_enable', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('db_type', models.ForeignKey(db_column='db_type', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='DbManage.DbCfgType')),
            ],
            options={
                'db_table': 'db_cfg_detail',
            },
        ),
    ]
